# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: CI & Release

on:
  push:
    branches: [ "master" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
    
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
        
      - name: Restore dependencies
        run: dotnet restore Weaver.sln
      
      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish Weaver.Abstractions (dry run)
        run: dotnet publish Weaver.Abstractions/Weaver.Abstractions.csproj -c Release -f netstandard2.0 --no-build --self-contained false

      - name: Publish Weaver (netstandard2.0 dry run)
        run: dotnet publish Weaver/Weaver.csproj -c Release -f netstandard2.0 --no-build --self-contained false

      - name: Publish Weaver (net8.0 dry run)
        run: dotnet publish Weaver/Weaver.csproj -c Release -f net8.0 --no-build --self-contained false

  semantic-release:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Install semantic-release
        run: npm install -g semantic-release @semantic-release/git @semantic-release/changelog @semantic-release/github

      - name: Run semantic-release
        run: semantic-release

  publish_nuget:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore Weaver.sln

      - name: Extract version from tag
        run: echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV

      - name: Pack Weaver.Abstractions
        run: dotnet pack Weaver.Abstractions/Weaver.Abstractions.csproj -c Release -o ./artifacts /p:Version=$VERSION

      - name: Pack Weaver
        run: dotnet pack Weaver/Weaver.csproj -c Release /p:UseProjectReferences=false -o ./artifacts /p:Version=$VERSION

      - name: Publish to NuGet
        run: dotnet nuget push "./artifacts/*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate

      - name: Publish symbols to NuGet
        run: dotnet nuget push "./artifacts/*.snupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
